version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=idb
      - POSTGRES_USER=idface
      - POSTGRES_PASSWORD=p@ssw0rd
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=idb
      - POSTGRES_USER=idface
      - POSTGRES_PASSWORD=p@ssw0rd
    depends_on:
      - db
